import { ai } from "@/lib/gemini";
import { NextRequest, NextResponse } from "next/server";
import { logger } from "@/lib/scaffold/logger";
import { AppError } from "@/lib/scaffold/errors";
import { AppErrorCode } from "@/lib/scaffold/types";

export async function POST(req: NextRequest) {
  const requestId = Math.random().toString(36).substring(7);
  try {
    const body = await req.json();
    const { prompt, referenceImage, style, refinement, upscale } = body;

    logger.log('API_START', 'IMAGE_GEN', `Processing generation request ${requestId}`, 'info', { prompt, style, refinement, upscale });

    if (!prompt) {
      throw new AppError(AppErrorCode.API_001, "Prompt is required", "IMAGE_GEN", "warn");
    }

    // Prepare contents
    const parts: any[] = [];
    
    let finalPrompt = prompt;
    
    // Apply style if provided
    if (style) {
      finalPrompt = `[Style: ${style}] - ${finalPrompt}`;
    }

    // Apply refinement if provided
    if (refinement) {
      finalPrompt = `[REFINEMENT: ${refinement}] - Ensure the previous character identity is maintained while applying these specific changes to this request: ${finalPrompt}`;
    }

    // Apply upscale hint if requested
    if (upscale) {
      finalPrompt = `${finalPrompt}. Extremely high quality, ultra-detailed, 8k resolution, crisp textures.`;
    }
    
    if (referenceImage) {
      parts.push({
        inlineData: {
          data: referenceImage.split(",")[1] || referenceImage,
          mimeType: "image/png",
        },
      });
      parts.push({
        text: `Using the provided character as a strict reference for identity, features, and style, generate an image of them: ${finalPrompt}. Ensure strong visual continuity.`,
      });
    } else {
      parts.push({
        text: finalPrompt,
      });
    }

    const response = await ai.models.generateContent({
      model: 'gemini-1.5-flash',
      contents: {
        parts: parts,
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
        },
      },
    });

    let imageUrl = "";
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData?.data) {
        const base64EncodeString: string = part.inlineData.data;
        imageUrl = `data:image/png;base64,${base64EncodeString}`;
        break;
      }
    }

    if (!imageUrl) {
      throw new AppError(AppErrorCode.AI_002, "No image was generated by the model", "IMAGE_GEN", "error");
    }

    logger.log('API_SUCCESS', 'IMAGE_GEN', `Generated image for request ${requestId}`, 'info');

    return NextResponse.json({ imageUrl });
  } catch (error: any) {
    if (error instanceof AppError) {
      return NextResponse.json(error.toJSON(), { status: error.severity === 'error' ? 500 : 400 });
    }
    
    const structuredError = new AppError(
      AppErrorCode.SYS_001,
      error.message || "Unknown error during image generation",
      "IMAGE_GEN",
      "error",
      { originalError: error.message }
    );
    return NextResponse.json(structuredError.toJSON(), { status: 500 });
  }
}
